name: bloc_code_generator
description: Bloc Code Generator is a code generator for https://github.com/felangel/bloc package.
version: 0.1.0
author: adson.leal <adsonpleal@gmail.com>
homepage: https://github.com/adsonpleal/bloc-code-generator


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.0.0
  analyzer: '>= 0.32.4 <=0.38.2'
  source_gen: ^0.9.0
