name: bloc_code_generator
description: A generator that makes working with bloc easier
version: 0.0.2
author: adson.leal <adsonpleal@gmail.com>
homepage: https://github.com/adsonpleal/bloc-code-generator


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: ^1.0.0
  analyzer: '>= 0.32.4 <0.36.0'
  source_gen: ^0.9.0
